[workspace]
members = [
    "gossip-protocol",
    "node",
    "partitioner",
    "query-coordinator",
    "testing",
]

[package]
name = "rustic-airlines"  # Asegúrate de que este nombre sea "rustic-airlines"
version = "0.1.0"

