[package]
name = "node_2"
version = "0.1.0"
edition = "2021"

[dependencies]
gossip = { path = "../gossip" }
internode_protocol = { path = "../internode_protocol" }
storage-engine = { path = "../storage-engine" }
clients-link = { path = "../clients-link" }
