[package]
name = "query-coordinator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
chrono = "0.4.38"
hex = "0.4.3"
native_protocol = { path = "../native_protocol" }
uuid = "1.11.0"
